export const authConstants = {
  ADMIN_LOGIN_REQUEST: "ADMIN_LOGIN_REQUEST",
  ADMIN_LOGIN_ACCEPT: "ADMIN_LOGIN_ACCEPT",
  ADMIN_LOGIN_FAILURE: "ADMIN_LOGIN_FAILURE",

  ADMIN_LOGOUT: "ADMIN_LOGOUT",

  ADMIN_REGISTER_REQUEST: "ADMIN_REGISTER_REQUEST",
  ADMIN_REGISTER_ACCEPT: "ADMIN_REGISTER_ACCEPT",
  ADMIN_REGISTER_FAILURE: "ADMIN_REGISTER_FAILURE",
};